# Generated by Django 3.2.9 on 2021-12-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30, null=True)),
                ('precio', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.IntegerField(choices=[[0, '8:00hrs. - 8:59hrs.'], [1, '9:00hrs. - 9:59hrs.'], [2, '10:00hrs. - 10:59hrs.'], [3, '11:00hrs. - 11:59hrs.'], [4, '12:00hrs. - 12:59hrs.'], [5, '13:00hrs. - 13:59hrs.'], [6, '14:00hrs. - 14:59hrs.']])),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fecha')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicio')),
            ],
        ),
    ]
